FROM ubuntu:24.04

# Do not run as root in production images
RUN apt-get update && \
    apt-get install -y --no-install-recommends curl && \
    rm -rf /var/lib/apt/lists/*

CMD ["bash", "-c", "echo Hello World && curl --version"]


