name: Build, Scan, and Push Docker Image to ECR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

env:
  AWS_REGION: ca-central-1
  IMAGE_NAME: 244822573207.dkr.ecr.ca-central-1.amazonaws.com/private/samv
  VERSION: v1.0.0

jobs:
  build-scan-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create environment variables file
        run: |
          env | grep "GITHUB_\|LW_\|CI_" > env.list
          echo "LW_ACCOUNT=${{ secrets.LW_ACCOUNT }}" >> env.list
          echo "LW_API_KEY=${{ secrets.LW_API_KEY }}" >> env.list
          echo "LW_API_SECRET=${{ secrets.LW_API_SECRET }}" >> env.list

      - name: Scan the repo for vulnerabilities in IaC
        run: |
          docker run --rm \
            --env-file env.list \
            -e EXIT_FLAG=low=1 \
            -v "$(pwd):/app/src" \
            -w /app/src \
            lacework/codesec:latest \
            lacework iac scan --directory=.
          echo "Lacework IaC scan exited with code $?"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract short SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build Docker image (scan-temp)
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: ${{ env.IMAGE_NAME }}:scan-temp

      - name: Scan image with Lacework inline scanner
        uses: lacework/lw-scanner-action@v1.4.0
        with:
          LW_ACCOUNT_NAME: ${{ secrets.LW_ACCOUNT_NAME }}
          LW_ACCESS_TOKEN: ${{ secrets.LW_ACCESS_TOKEN }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          IMAGE_TAG: scan-temp
          SAVE_RESULTS_IN_LACEWORK: true
          RESULTS_IN_GITHUB_SUMMARY: true

      - name: Format scan results for PR comment
        if: github.event_name == 'pull_request'
        run: |
          echo "# Lacework Inline Scanner Result" > pr-results.md
          echo "<pre>" >> pr-results.md
          echo "Scan completed. See the GitHub Summary above or view results in Lacework." >> pr-results.md
          echo "</pre>" >> pr-results.md

      - name: Comment PR with scan summary
        if: github.event_name == 'pull_request'
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: pr-results.md

      - name: Build and Push Docker image to ECR
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ env.VERSION }}
            ${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.sha_short }}
