name: Build, Scan, and Push Docker Image to ECR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

env:
  AWS_REGION: ca-central-1
  IMAGE_NAME: 244822573207.dkr.ecr.ca-central-1.amazonaws.com/private/samv
  VERSION: v1.0.0

jobs:
  build-scan-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract short SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build Docker image (scan-temp)
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: ${{ env.IMAGE_NAME }}:scan-temp

      - name: Scan image with Lacework Docker scanner
        run: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -e LW_ACCOUNT_NAME=${{ secrets.LW_ACCOUNT_NAME }} \
            -e LW_API_TOKEN=${{ secrets.LW_ACCESS_TOKEN }} \
            lacework/lw-scanner \
            image evaluate ${{ env.IMAGE_NAME }}:scan-temp > results.stdout

          echo "Checking for policy violations..."
          if grep -q "Policy.*failed" results.stdout; then
            echo "❌ Lacework policy violation found. Failing job."
            exit 1
          else
            echo "✅ No policy violations."
          fi

      - name: Format scan results for PR comment
        if: github.event_name == 'pull_request'
        run: |
          echo "# Lacework Inline Scanner Result" > pr-results.md
          echo "<pre>" >> pr-results.md
          cat results.stdout >> pr-results.md || echo "No scan results found." >> pr-results.md
          echo "</pre>" >> pr-results.md

      - name: Comment PR with scan results
        if: github.event_name == 'pull_request'
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: pr-results.md

      - name: Build and Push Docker Image to ECR
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ env.VERSION }}
            ${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.sha_short }}
