name: CodeSec IaC Scanning Terraform

on:
  push:
    branches: [ "main" ]
    paths:
      - '**/*.tf'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**/*.tf'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create environment variables file
        run: |
          env | grep "GITHUB_\|LW_\|CI_" > env.list
          echo "LW_ACCOUNT=${{ secrets.LW_ACCOUNT }}" >> env.list
          echo "LW_API_KEY=${{ secrets.LW_API_KEY }}" >> env.list
          echo "LW_API_SECRET=${{ secrets.LW_API_SECRET }}" >> env.list
          echo "EXIT_FLAG=CRITICAL=1" >> env.list
          echo "JSON_OUTPUT_FILE=report.json" >> env.list


      - name: Prepare workspace
        run: chmod -R 777 "$(pwd)"

      - name: Run Lacework IaC Scan
        id: lacework_scan
        run: |
          docker run \
            --env-file env.list \
            -v "$(pwd):/app/src" \
            lacework/codesec:stable \
            lacework iac scan --directory=/app/src --save-result /app/src/report.json

      - name: Detect critical/high issues but don't fail yet
        id: scan_result
        run: |
          jq -e '.findings | any(.severity=="CRITICAL" or .severity=="HIGH")' report.json > /dev/null
          echo "exit_code=$?" >> $GITHUB_OUTPUT

      - name: Upload report.json as artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: lacework-iac-report
          path: report.json

      - name: Fail job if issues found
        if: ${{ steps.scan_result.outputs.exit_code == '0' }}
        run: |
          echo "❌ Critical or High severity issues found"
          exit 1

            

  

