name: lacework-iac-example

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events to the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows manual trigger from the Actions tab
  workflow_dispatch:

# Workflow jobs
jobs:
  build:
    # Runner type
    runs-on: ubuntu-24.04

    # Job steps
    steps:
      # Step 1: Checkout repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Prepare workspace
        run: chmod -R 777 "$(pwd)"

      # Step 2: Create environment variables file
      - name: Create environment variables file
        run: |
          env | grep "GITHUB_\|LW_\|CI_" > env.list
          echo "LW_ACCOUNT=${{ secrets.LW_ACCOUNT }}" >> env.list
          echo "LW_API_KEY=${{ secrets.LW_API_KEY }}" >> env.list
          echo "LW_API_SECRET=${{ secrets.LW_API_SECRET }}" >> env.list
          echo "EXIT_FLAG=CRITICAL=1" >> env.list

      # Step 3: Run Lacework IaC scan
      - name: Scan the repo for vulnerabilities in IaC
        run: |
          docker run \
            --env-file env.list \
            -v "$(pwd):/app/src" \
            lacework/codesec:stable \
            lacework iac scan --directory=. --exit-code hard=1 --debug
