name: CodeSec IaC Scanning Terraform

on:
  push:
    branches: [ "main" ]
    paths:
      - '**/*.tf'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**/*.tf'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create environment variables file
        run: |
          env | grep "GITHUB_\|LW_\|CI_" > env.list
          echo "LW_ACCOUNT=${{ secrets.LW_ACCOUNT }}" >> env.list
          echo "LW_API_KEY=${{ secrets.LW_API_KEY }}" >> env.list
          echo "LW_API_SECRET=${{ secrets.LW_API_SECRET }}" >> env.list
          echo "EXIT_FLAG=CRITICAL=1" >> env.list
          echo "JSON_OUTPUT_FILE=report.json" >> env.list


      - name: Prepare workspace
        run: chmod -R 777 "$(pwd)"

      - name: Run Lacework IaC Scan
        id: lacework_scan
        run: |
          docker run \
            --env-file env.list \
            -v "$(pwd):/app/src" \
            lacework/codesec:stable \
            lacework iac scan --directory=/app/src --save-result /app/src/report.json

      - name: Fail on CRITICAL or HIGH non-compliance
        run: |
          if [ ! -f report.json ]; then
            echo "report.json not found! Assuming scan failed or no results. Failing the build."
            exit 1
          fi

          if jq -e '.findings | any(.severity=="Critical" or .severity=="High")' report.json; then
            echo "Critical or High severity issues found. Failing the build."
            exit 1
          else
            echo "No critical or high severity issues found."
          fi

      - name: Upload report.json as artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: lacework-iac-report
          path: report.json

            

  

