name: Lacework Container Image Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  scan-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t myapp:v1.0.0 .

      - name: Scan container image for vulnerabilities using Lacework
        uses: lacework/lw-scanner-action@v1.4.0
        with:
          LW_ACCOUNT: ${{ secrets.LW_ACCOUNT }}
          LW_ACCESS_TOKEN: ${{ secrets.LW_ACCESS_TOKEN }}
          IMAGE_NAME: myapp
          IMAGE_TAG: v1.0.0



         
