name: Lacework Docker Container Image Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  IMAGE_NAME: samv_is_docker
  IMAGE_TAG: v1.0.2

jobs:
  scan-container:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .

      - name: Run Vulnerability Scan with Lacework Inline Scanner
        env:
          LW_ACCOUNT_NAME: ${{ secrets.LW_ACCOUNT_NAME }}
          LW_ACCESS_TOKEN: ${{ secrets.LW_ACCESS_TOKEN }}
          LW_SCANNER_SAVE_RESULTS: "true"
          DEBUG: "true"
        run: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -e LW_ACCOUNT_NAME=$LW_ACCOUNT_NAME \
            -e LW_ACCESS_TOKEN=$LW_ACCESS_TOKEN \
            -e LW_SCANNER_SAVE_RESULTS=$LW_SCANNER_SAVE_RESULTS \
            -e DEBUG=$DEBUG \
            lacework/lacework-inline-scanner:latest --policy --fail-on-violation-exit-code 1 \
            image evaluate ${{ env.IMAGE_NAME }} ${{ env.IMAGE_TAG }} --save
