name: Lacework Container Image Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  IMAGE_NAME: myapp
  IMAGE_TAG: v1.0.0
  FULL_IMAGE_NAME: myapp:v1.0.0

jobs:
  scan-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t ${{ env.FULL_IMAGE_NAME }} .

      - name: Scan container image for vulnerabilities using Lacework
        uses: lacework/lw-scanner-action@v1.4.5
        with:
          LW_ACCOUNT_NAME: ${{ secrets.LW_ACCOUNT_NAME }}
          LW_ACCESS_TOKEN: ${{ secrets.LW_ACCESS_TOKEN }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
          SAVE_RESULTS_IN_LACEWORK: true
          RESULTS_IN_GITHUB_SUMMARY: true
          DEBUGGING: true 
         

      - name: Format Lacework results for PR comment
        run: |
          echo "# Lacework Scanner Results" > pr-results.md
          echo "✅ Scan completed using Lacework." >> pr-results.md
          echo "📊 See results in the **GitHub Actions Summary tab** or in the **Lacework Console**." >> pr-results.md

      - name: Comment on Pull Request
        if: github.event_name == 'pull_request'
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: pr-results.md
