name: Lacework Container Image Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  IMAGE_NAME: myapp
  IMAGE_TAG: v1.0.0
  FULL_IMAGE_NAME: myapp:v1.0.0

jobs:
  scan-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t ${{ env.FULL_IMAGE_NAME }} .

      - name: Run vulnerability scan with Lacework inline scanner
        env:
          LW_ACCOUNT: ${{ secrets.LW_ACCOUNT_NAME }}
          LW_API_TOKEN: ${{ secrets.LW_ACCESS_TOKEN }}
        run: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -e LW_ACCOUNT=$LW_ACCOUNT \
            -e LW_API_TOKEN=$LW_API_TOKEN \
            lacework/lacework-inline-scanner:latest \
            image scan ${{ env.IMAGE_NAME }} ${{ env.IMAGE_TAG }}

      - name: Evaluate public image ubuntu:latest
        run: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            lacework/lacework-inline-scanner:latest \
            image evaluate ubuntu:latest

      - name: Format Lacework results for PR comment
        run: |
          echo "# Lacework Scanner Results" > pr-results.md
          echo "✅ Scans completed using Lacework Inline Scanner." >> pr-results.md
          echo "📊 See details in GitHub Actions logs and the Lacework Console." >> pr-results.md

      - name: Comment on Pull Request
        if: github.event_name == 'pull_request'
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: pr-results.md
