name: Lacework Container Image Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  scan-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t myapp:latest .

      - name: Scan Docker image with Lacework
        env:
          LW_ACCOUNT: ${{ secrets.LW_ACCOUNT }}
          LW_ACCESS_TOKEN: ${{ secrets.LW_ACCOUNT }}
  
        run: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -e LW_ACCOUNT=$LW_ACCOUNT \
            -e LW_ACCESS_TOKEN=$LW_ACCESS_TOKEN \
            lacework/lacework-inline-scanner:latest \
            image scan myapp:latest


         
