name: lacework-iac-example

on:
  push:
    branches: ["main"]
    paths:
      - '**.tf'
  pull_request:
    branches: ["main"]
    paths:
      - '**.tf'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create environment variables file
        run: |
          env | grep "GITHUB_\|LW_\|CI_" > env.list
          echo "LW_ACCOUNT=${{ secrets.LW_ACCOUNT }}" >> env.list
          echo "LW_API_KEY=${{ secrets.LW_API_KEY }}" >> env.list
          echo "LW_API_SECRET=${{ secrets.LW_API_SECRET }}" >> env.list
          echo "EXIT_FLAG=high=1" >> env.list 
          #echo "EXIT_FLAG=HIGH=1" >> env.list 

      - name: Set directory permissions
        run: |
          mkdir -p .terraform
          chmod -R 777 .terraform

      - name: Scan the repo for vulnerabilities in IaC
        run: |
          docker run --env-file env.list \
            -v "$(pwd):/app/src:rw" \
            -w /app/src \
            lacework/codesec:stable \
            lacework iac scan --directory=. 
