name: Terraform + Lacework Scan

on:
  push:
    branches: ["main"]
    paths:
      - '**.tf'
  pull_request:
    branches: ["main"]
    paths:
      - '**.tf'
  workflow_dispatch:

jobs:
  terraform-lacework-iac:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init (Writable)
        run: terraform init

      - name: Create environment variable file
        run: |
          env | grep "GITHUB_\|LW_\|CI_" > env.list
          echo "LW_ACCOUNT=${{ secrets.LW_ACCOUNT }}" >> env.list
          echo "LW_API_KEY=${{ secrets.LW_API_KEY }}" >> env.list
          echo "LW_API_SECRET=${{ secrets.LW_API_SECRET }}" >> env.list
          echo "EXIT_FLAG=high=1" >> env.list

      - name: Run Lacework IaC scan and check severity
        run: |
          docker run --rm --env-file env.list \
            -v "$(pwd):/app/src:rw" \
            -w /app/src \
            lacework/codesec:stable \
            lacework iac scan --directory=. > iac-scan.txt

          echo "Scan complete. Checking severity..."
          if grep -qE 'Severity:\s+(Medium|High|Critical)' iac-scan.txt; then
            echo "Vulnerabilities of Medium or higher severity found:"
            cat iac-scan.txt
            exit 1
          else
            echo "No Medium, High, or Critical severity issues found."
          fi
