name: Lacework IaC Scan

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  iac-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Create Lacework env.list
        run: |
          echo "LW_ACCOUNT=${{ secrets.LW_ACCOUNT }}" >> env.list
          echo "LW_API_KEY=${{ secrets.LW_API_KEY }}" >> env.list
          echo "LW_API_SECRET=${{ secrets.LW_API_SECRET }}" >> env.list
          echo "EXIT_FLAG=CRITICAL=1,HIGH=1" >> env.list
          echo "CI_REPO_URL=https://github.com/${{ github.repository }}" >> env.list

      - name: Run Lacework IaC Scan (your exact command)
        run: |
          docker run --rm \
            --env-file env.list \
            -v "$(pwd):/app/src" \
            -w /app/src \
            lacework/codesec:stable \
            lacework iac scan --directory=.
