name: Lacework IaC Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create environment variables file
        run: |
          echo "LW_ACCOUNT=${{ secrets.LW_ACCOUNT }}" >> env.list
          echo "LW_API_KEY=${{ secrets.LW_API_KEY }}" >> env.list
          echo "LW_API_SECRET=${{ secrets.LW_API_SECRET }}" >> env.list
          echo "EXIT_FLAG=CRITICAL=1,HIGH=1" >> env.list

      - name: Run Lacework IaC Scan (Terraform only)
        run: |
          docker run --env-file env.list \
            -v "$(pwd):/src" \
            lacework/codesec:stable \
            /bin/sh -c "mkdir -p /tmp/scan && find /src -name '*.tf' -exec cp --parents {} /tmp/scan \; && lacework iac scan --directory=/tmp/scan"
           


