name: Lacework ECR Image Scan

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: ca-central-1
  IMAGE_URI: 244822573207.dkr.ecr.ca-central-1.amazonaws.com/private/samv:samv_dvwa

jobs:
  scan-with-lacework-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | \
            docker login --username AWS --password-stdin 244822573207.dkr.ecr.ca-central-1.amazonaws.com

      - name: Pull Docker Image from ECR
        run: |
          docker pull $IMAGE_URI

      - name: Run Lacework Container Scanner
        uses: lacework/scanner-action@v1
        with:
          image: ${{ env.IMAGE_URI }}
        env:
          LW_ACCOUNT_NAME: ${{ secrets.LW_ACCOUNT_NAME }}
          LW_API_TOKEN: ${{ secrets.LW_API_TOKEN }}
